### ISSUE TITLE
Some metrics proposals

### ISSUE THREAD

**Issue by matentzn** [cthoyt/obo-community-health#1]
@cthoyt this is super cool! Thanks for doing it. 

Here some metrics I would find incredible useful:

- [x] Number of distinct github users that made a push
- [x] Number of distinct github users that provided a comment (in an issue, or a pr)
- [x] Number of pushes in the last 12 months
- [x] Using modern ODK or not (this can be done by a simple lookup for the file src/ontology/ontid-odk.yaml)

To be honest, I don't care how broad the table becomes.. Its really about the content, not the user experience..

**Comment by cthoyt** [comment]
1. Done in 647da69
2. Number of users providing a comment probably won't be fast... might require scraping all issues. That's possible, though! 
3. I added number of pushes in last year in 647da69. Not sure what to average over
4. Working on this

**Comment by matentzn** [comment]
3. Number of pushes in last year is perfect

**Comment by cthoyt** [comment]
ODK report added in https://github.com/cthoyt/obo-community-health/commit/c420fed7b9a666b421160caf2ef88151a16f06af, all of these suggestions are now implemented!
