### ISSUE TITLE
OMRSE uses ODK 1.3.0 but shows up as not using ODK

### ISSUE THREAD

**Issue by hoganwr** [cthoyt/obo-community-health#17]
Not sure why at this point, but OMRSE is using ODK 1.3.0 (per the src/ontology/Makefile), but in the community health summary, it shows with a red dot as not using ODK. as well as in the Messages column it says "Not using ODK".

**Comment by cthoyt** [comment]
This list is somewhat auto-generated using GitHub's search API, which has proven very unstable. We can add it directly to https://github.com/cthoyt/obo-community-health/blob/main/data/odk_repos.tsv
