### ISSUE TITLE
Add list of all ontology ids in OBO that are _not_ covered

### ISSUE THREAD

**Issue by matentzn** [cthoyt/obo-community-health#5]
I would like a simple sentence on the frontpage like:

"The following ontologies are not covered by this dashboard because they do not make use of GitHub repos: a, b, c, d."

This way we avoid the justified accusation that some repos would appear at the bottom, but actually are very active (for example PRO).

**Comment by matentzn** [comment]
In fact, I would not have any ontologies appear in the table if they cant be accurately represented.

**Comment by cthoyt** [comment]
Agreed, though I believe using a system other than GitHub (presently) will likely be shown to be hugely negatively correlated with community involvement

**Comment by matentzn** [comment]
Not entirely sure.. Lets check on a case by case basis :) As I said: think of PRO!

**Comment by cthoyt** [comment]
Looking back into this, it does appear PRO has a github repo https://github.com/PROconsortium/PRoteinOntology, but I guess this isn't where they do their work?

**Comment by cthoyt** [comment]
Either way with the next push I will make sure that all (non depecated/orphaned/abandoned) ontologies are represented, and then there's a score associated with each. Obviously not doing curation in a GitHub repository will be a huge detriment, but unless there's a reason that my implementation shouldn't be opinionated (e.g., the community wants to make it more official and more political) then I don't see a good reason not to have these kinds of practices reflected

**Comment by cthoyt** [comment]
The three ontologies that don't use github (OGG, MAMO, and ONTOAVIDA) are all represented (and will continue to be). As suspected, it's pretty obvious that they take a huge hit on community engagement because of their non-github status
