### ISSUE TITLE
OBO community health does not show ODK config correctly

### ISSUE THREAD

**Issue by matentzn** [cthoyt/obo-community-health#7]
![image](https://user-images.githubusercontent.com/7070631/150204869-d11c1c3d-3070-4ab5-b755-15982cbaf7d8.png)

hp, cl, uberon, omrse, pato all have ODKs..

**Comment by matentzn** [comment]
I would also rename the metric to `ODK repo` or `Uses ODK` or some such.. `Config` isn't really all that meaningful.

**Comment by cthoyt** [comment]
the ODK flag doesn't currently get populated by real information because the GitHub search has a pretty restrictive rate limit and I don't know a better way to get this. I will have to write a new script that runs slower and less frequently

**Comment by cthoyt** [comment]
Solved in c420fed
