### ISSUE TITLE
FlyBase and VFB ontologies no longer detected as ODK

### ISSUE THREAD

**Issue by Clare72** [cthoyt/obo-community-health#8]
As of yesterday's "Add ODK versions" commit, the four FlyBase ontologies and two VitualFlyBrain ontologies no longer feature in the odk_repos.yaml file:

[data/odk_repos.yaml](https://github.com/cthoyt/obo-community-health/commit/c1e3dd65c81881e7d9ff67e5e5c2877e132d7c31#diff-d8fe52a2e57c792aff2d3ff95ae5505eae4d7f66ace7ee7ab65e3e9fc049fd3d)

(They are still ODK!)

**Comment by cthoyt** [comment]
Hi @Clare72, I'm sorry that this has caused you some frustration. In fact, I knew that there were some instability issues with the GitHub API that made the results a bit incorrect. I just wrote a further explanation on #9. I will do my best to get this fixed ASAP to best represent your and others ontologies :)
